### ISSUE TITLE
Please add support for multiple values in aws_statistics

### ISSUE THREAD

**Issue by jonathansm1th** [Technofy/cloudwatch_exporter#19]
Adding a metric with more than one value in `aws_statistics` throws error:

```
* collected metric "aws_lambda_duration_maximum" { label:<name:"function_name" value:"LambdaFunctionName" > label:<name:"task" value:"lambda_duration_no_select" > gauge:<value:290.72 > } was collected before with the same name and label values
```

```yaml
 - name: lambda_duration_no_select
   default_region: us-east-1
   metrics:
    - aws_namespace: "AWS/Lambda"
      aws_dimensions: [FunctionName]
      aws_metric_name: Duration
      aws_statistics: [Maximum, Minimum]
```
